# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a9a3b365fd9e1f92160cf1e5ea8b2224e36bdc1a38f1553b080eae892b7ee31efabd760c768c23549d83148393e99edbf33e6387a7eb3a0b714462c64429a962

test:
  secret_key_base: 7ca38d758892c85ce0967cd8f5fc8ed0945f4227c995e5fc45b1245e7a0b00cf88dc815e7d12ec3e544110cfa9b7453b72d9b0166fef4b6d83279c18ee5fe41c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
